apiVersion: apps/v1
kind: Deployment
metadata:
  name: rg4r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rg4r
  template:
    metadata:
      labels:
        app: rg4r
    spec:
      containers:
      - image: okteto.dev/rg4r:latest
        name: rg4r
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "5b53033c-413e-4409-b513-57b6156a922d"
        - name: Vless_Path
          value: "/trydf"
        - name: Vmess_UUID
          value: "5b53033c-413e-4409-b513-57b6156a922d"
        - name: Vmess_Path
          value: "/gyhtry"
        - name: Share_Path
          value: "/share233"
