apiVersion: apps/v1
kind: Deployment
metadata:
  name: erwd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erwd
  template:
    metadata:
      labels:
        app: erwd
    spec:
      containers:
      - image: okteto.dev/erwd:latest
        name: erwd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "0c63d9f3-29b0-4549-b331-9dbf277e5032"
        - name: Vless_Path
          value: "/dsfrt"
        - name: Vmess_UUID
          value: "0c63d9f3-29b0-4549-b331-9dbf277e5032"
        - name: Vmess_Path
          value: "/gfhu"
        - name: Share_Path
          value: "/share233"
