apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgh
  template:
    metadata:
      labels:
        app: bgh
    spec:
      containers:
      - image: okteto.dev/bgh:latest
        name: bgh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "275a1a6b-7a09-4a5e-9c34-bd1276f5da81"
        - name: Vless_Path
          value: "/dfgrt"
        - name: Vmess_UUID
          value: "275a1a6b-7a09-4a5e-9c34-bd1276f5da81"
        - name: Vmess_Path
          value: "/vdsf"
        - name: Share_Path
          value: "/share233"
