apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsrf
  template:
    metadata:
      labels:
        app: wsrf
    spec:
      containers:
      - image: okteto.dev/wsrf:latest
        name: wsrf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "1e3fb5d0-3101-4a58-9158-ca3b4b67cc9f"
        - name: Vless_Path
          value: "/cxvgt"
        - name: Vmess_UUID
          value: "1e3fb5d0-3101-4a58-9158-ca3b4b67cc9f"
        - name: Vmess_Path
          value: "/ewrfs"
        - name: Share_Path
          value: "/share233"
