apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkhk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkhk
  template:
    metadata:
      labels:
        app: mkhk
    spec:
      containers:
      - image: okteto.dev/mkhk:latest
        name: mkhk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "e28f6a8d-ef08-4fda-9a5d-a10b57633627"
        - name: Vless_Path
          value: "/acpourd"
        - name: Vmess_UUID
          value: "e28f6a8d-ef08-4fda-9a5d-a10b57633627"
        - name: Vmess_Path
          value: "/ueredeg"
        - name: Share_Path
          value: "/share233"
