apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ewr
  template:
    metadata:
      labels:
        app: ewr
    spec:
      containers:
      - image: okteto.dev/ewr:latest
        name: ewr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "0a8fc5a7-b2f0-4e20-b59f-08c74dc63baa"
        - name: Vless_Path
          value: "/acpourd"
        - name: Vmess_UUID
          value: "0a8fc5a7-b2f0-4e20-b59f-08c74dc63baa"
        - name: Vmess_Path
          value: "/ueredeg"
        - name: Share_Path
          value: "/share233"
