apiVersion: apps/v1
kind: Deployment
metadata:
  name: hun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hun
  template:
    metadata:
      labels:
        app: hun
    spec:
      containers:
      - image: okteto.dev/hun:latest
        name: hun
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "17bd4795-1380-46c8-87a4-8b3732619851"
        - name: Vless_Path
          value: "/eufgy"
        - name: Vmess_UUID
          value: "17bd4795-1380-46c8-87a4-8b3732619851"
        - name: Vmess_Path
          value: "/njkg"
        - name: Share_Path
          value: "/share233"
