apiVersion: v1
kind: Service
metadata:
  name: rg4r
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "rg4r"
    port: 8080
  selector:
    app: rg4r
